# Generated by Django 2.2.5 on 2019-09-18 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('id_binacle', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=50)),
                ('start_kilometer', models.FloatField()),
                ('end_kilometer', models.FloatField()),
                ('start_fuel', models.FloatField()),
                ('end_fuel', models.FloatField()),
                ('start_datetime', models.DateTimeField(max_length=6)),
                ('end_datetime', models.DateTimeField(max_length=6)),
                ('fuel_voucher', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(max_length=6)),
            ],
            options={
                'verbose_name': 'bitacora',
                'verbose_name_plural': 'bitacoras',
                'db_table': 'binnacle',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'conductor',
                'verbose_name_plural': 'conductores',
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=70)),
                ('from_depto', models.CharField(max_length=70)),
                ('datetime', models.DateTimeField(max_length=6, null=True)),
                ('description', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_vehicle', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=20)),
                ('data_service', models.DateTimeField(max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='DriverBinacleService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, max_length=6)),
                ('binnacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Binnacle')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Driver')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Service')),
            ],
            options={
                'db_table': 'DriverBinacleService',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='binnacles',
            field=models.ManyToManyField(related_name='idBinnacle', through='fleetservice.DriverBinacleService', to='fleetservice.Binnacle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='services',
            field=models.ManyToManyField(related_name='idBinnacle', through='fleetservice.DriverBinacleService', to='fleetservice.Service'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Vehicle'),
        ),
    ]
