# Generated by Django 2.2.5 on 2019-09-30 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('id_binacle', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(choices=[('Seleccion', 'Selecciona una opción'), ('Playa-Corporativo', 'Playa del Carmen - Corporativo'), ('Corporativo-Playa', 'Corporativo - Playa del Carmen')], default='Seleccion', max_length=50)),
                ('start_kilometer', models.FloatField()),
                ('end_kilometer', models.FloatField()),
                ('datetime', models.DateTimeField(max_length=6)),
                ('start_time', models.TimeField(max_length=6)),
                ('end_time', models.TimeField(max_length=6)),
                ('created_at', models.DateTimeField(max_length=6)),
            ],
            options={
                'verbose_name': 'bitacora',
                'verbose_name_plural': 'bitacoras',
                'db_table': 'binnacle',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('license_expedition', models.DateTimeField(max_length=6)),
                ('license_expiration', models.DateTimeField(max_length=6)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'conductor',
                'verbose_name_plural': 'conductores',
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=70)),
                ('from_depto', models.CharField(max_length=70)),
                ('start_kilometer', models.FloatField(null=True)),
                ('end_kilometer', models.FloatField(null=True)),
                ('datetime', models.DateTimeField(max_length=6, null=True)),
                ('start_time', models.TimeField(max_length=6)),
                ('end_time', models.TimeField(max_length=6)),
                ('description', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_vehicle', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=20)),
                ('data_service', models.DateTimeField(max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id_refuel', models.AutoField(primary_key=True, serialize=False)),
                ('liters', models.FloatField(max_length=50)),
                ('amount', models.FloatField(max_length=50)),
                ('datetime', models.DateTimeField(max_length=6)),
                ('image', models.FileField(upload_to='documents/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='fleetservice.Vehicle')),
            ],
            options={
                'verbose_name': 'recarga',
                'verbose_name_plural': 'recargas',
                'db_table': 'refuel',
            },
        ),
        migrations.CreateModel(
            name='DriverService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, max_length=6)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Driver')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Service')),
            ],
            options={
                'db_table': 'DriverService',
            },
        ),
        migrations.CreateModel(
            name='DriverRefuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, max_length=6)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Driver')),
                ('refuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Refuel')),
            ],
            options={
                'db_table': 'DriverRefuel',
            },
        ),
        migrations.CreateModel(
            name='DriverBinacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, max_length=6)),
                ('binnacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Binnacle')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Driver')),
            ],
            options={
                'db_table': 'DriverBinacle',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='binnacles',
            field=models.ManyToManyField(related_name='driverBinacle', through='fleetservice.DriverBinacle', to='fleetservice.Binnacle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='refuels',
            field=models.ManyToManyField(related_name='driverRefuel', through='fleetservice.DriverRefuel', to='fleetservice.Refuel'),
        ),
        migrations.AddField(
            model_name='driver',
            name='services',
            field=models.ManyToManyField(related_name='driverService', through='fleetservice.DriverService', to='fleetservice.Service'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Vehicle'),
        ),
    ]
