# Generated by Django 2.2.5 on 2019-10-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Vehicle'),
        ),
    ]
