# Generated by Django 2.2.5 on 2019-09-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleetservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driver',
            table='driver',
        ),
    ]
