# Generated by Django 2.2.5 on 2019-09-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetservice', '0002_auto_20190918_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
