# Generated by Django 2.2.5 on 2019-09-24 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetservice', '0003_driver_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binnacle',
            name='route',
            field=models.CharField(choices=[('Seleccion', 'Selecciona una opción'), ('Playa-Corporativo', 'Playa del Carmen-Oficinas'), ('Corporativo-Playa', 'Ofcinas-Playa del Carmen')], default='Seleccion', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
