# Generated by Django 2.2.5 on 2019-09-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetservice', '0004_auto_20190924_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBinacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, max_length=6)),
            ],
            options={
                'db_table': 'DriverBinacle',
            },
        ),
        migrations.CreateModel(
            name='DriverRefuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, max_length=6)),
            ],
            options={
                'db_table': 'DriverRefuel',
            },
        ),
        migrations.CreateModel(
            name='DriverService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, max_length=6)),
            ],
            options={
                'db_table': 'DriverService',
            },
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id_refuel', models.AutoField(primary_key=True, serialize=False)),
                ('liters', models.FloatField(max_length=50)),
                ('amount', models.FloatField(max_length=50)),
                ('datetime', models.DateTimeField(max_length=6)),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'recarga',
                'verbose_name_plural': 'recargas',
                'db_table': 'refuel',
            },
        ),
        migrations.RemoveField(
            model_name='binnacle',
            name='end_fuel',
        ),
        migrations.RemoveField(
            model_name='binnacle',
            name='fuel_voucher',
        ),
        migrations.RemoveField(
            model_name='binnacle',
            name='start_fuel',
        ),
        migrations.AlterField(
            model_name='binnacle',
            name='route',
            field=models.CharField(choices=[('Seleccion', 'Selecciona una opción'), ('Playa-Corporativo', 'Playa del Carmen - Corporativo'), ('Corporativo-Playa', 'Corporativo - Playa del Carmen')], default='Seleccion', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='binnacles',
            field=models.ManyToManyField(related_name='driverBinacle', through='fleetservice.DriverBinacle', to='fleetservice.Binnacle'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='services',
            field=models.ManyToManyField(related_name='driverService', through='fleetservice.DriverService', to='fleetservice.Service'),
        ),
        migrations.DeleteModel(
            name='DriverBinacleService',
        ),
        migrations.AddField(
            model_name='driverservice',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Driver'),
        ),
        migrations.AddField(
            model_name='driverservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Service'),
        ),
        migrations.AddField(
            model_name='driverrefuel',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Driver'),
        ),
        migrations.AddField(
            model_name='driverrefuel',
            name='refuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Refuel'),
        ),
        migrations.AddField(
            model_name='driverbinacle',
            name='binnacle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Binnacle'),
        ),
        migrations.AddField(
            model_name='driverbinacle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetservice.Driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='refuels',
            field=models.ManyToManyField(related_name='driverRefuel', through='fleetservice.DriverRefuel', to='fleetservice.Refuel'),
        ),
    ]
