# Generated by Django 2.2.5 on 2019-09-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetservice', '0005_auto_20190924_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_kilometer',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_kilometer',
            field=models.FloatField(null=True),
        ),
    ]
