# Generated by Django 2.2.5 on 2019-09-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('lastP', models.CharField(blank=True, max_length=20)),
                ('lastM', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, max_length=6)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
    ]
